### ISSUE TITLE
Crash during first execution

### ISSUE THREAD

**Issue by kavod** [Arn-O/py-kodi-remote-controller#31]
![capture du 2015-04-20 19 56 24](https://cloud.githubusercontent.com/assets/5834316/7236806/7c975c52-e797-11e4-8008-9b03653d4998.png)

**Comment by Arn-O** [comment]
Nice screenshot.

Error message with high verbosity:

```
INFO:root:Processing song 360 to 380 ...
DEBUG:root:call call_api_http
DEBUG:root:command: {'params': {'properties': ['title', 'artist', 'year', 'rating', 'playcount', 'musicbrainztrackid'], 'limits': {'start': 360, 'end': 380}}, 'jsonrpc': '2.0', 'method': 'AudioLibrary.GetSongs', 'id': 1}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.10
DEBUG:requests.packages.urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 3441
DEBUG:root:url: http://192.168.0.10:8080/jsonrpc
DEBUG:root:status code: 200
DEBUG:root:text: {"id":1,"jsonrpc":"2.0","result":{"limits":{"end":380,"start":360,"total":3728},"songs":[{"artist":["Mike Brant"],"label":"01 Qui saura (remix)","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21468,"title":"01 Qui saura (remix)","year":0},{"artist":["Mike Brant"],"label":"09 L'oiseau noir et l'oiseau b","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21469,"title":"09 L'oiseau noir et l'oiseau b","year":0},{"artist":["Mike Brant"],"label":"12 Qui saura (karaokÃ©)","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21470,"title":"12 Qui saura (karaokÃ©)","year":0},{"artist":[],"label":"Si j'avais un marteau","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21471,"title":"Si j'avais un marteau","year":0},{"artist":["Claude Francois"],"label":"Avec La TÃªte, Avec Le Coeur","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21472,"title":"Avec La TÃªte, Avec Le Coeur","year":2000},{"artist":["Claude Francois"],"label":"Ca s'en va et ca revient","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21473,"title":"Ca s'en va et ca revient","year":0},{"artist":["Claude Francois"],"label":"Magnolias 2001 (Club)","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21474,"title":"Magnolias 2001 (Club)","year":2001},{"artist":["Claude Francois"],"label":"Gens qui pleurent , gens qui r","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21475,"title":"Gens qui pleurent , gens qui r","year":0},{"artist":["Claude Francois"],"label":"Je vais a Rio","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21476,"title":"Je vais a Rio","year":0},{"artist":["Claude Francois"],"label":"Le chanteur malheureux","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21477,"title":"Le chanteur malheureux","year":0},{"artist":["Claude Francois"],"label":"- Le Jouet Extraordinaire","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21478,"title":"- Le Jouet Extraordinaire","year":0},{"artist":["Claude Francois"],"label":"Magnolias for ever","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21479,"title":"Magnolias for ever","year":0},{"artist":["Claude Francois"],"label":"Y' a le printemps qui chante","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21480,"title":"Y' a le printemps qui chante","year":0},{"artist":["Claude Francois"],"label":"Belinda","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21481,"title":"Belinda","year":2000},{"artist":["Claude Francois"],"label":"claude francois","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21482,"title":"claude francois","year":0},{"artist":["Claude Francois"],"label":"Sale bonhomme","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21483,"title":"Sale bonhomme","year":0},{"artist":["Claude Francois"],"label":"C'est comme Ã§a que l'on s'est aimÃ©","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21484,"title":"C'est comme Ã§a que l'on s'est aimÃ©","year":1977},{"artist":["Claude Francois"],"label":"C'est La Meme Chanson","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21485,"title":"C'est La Meme Chanson","year":0},{"artist":["Claude Francois"],"label":"Cette Annee La","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21486,"title":"Cette Annee La","year":0},{"artist":["Claude Francois"],"label":"Comme D'habitude","musicbrainztrackid":"","playcount":0,"rating":0,"songid":21487,"title":"Comme D'habitude","year":0}]}}
Traceback (most recent call last):
  File "pykodi.py", line 1080, in <module>
    main()
  File "pykodi.py", line 1077, in main
    remote_controller.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "pykodi.py", line 820, in preloop
    get_audio_library(self)
  File "pykodi.py", line 151, in get_audio_library
    get_audio_library_from_server(obj)
  File "pykodi.py", line 208, in get_audio_library_from_server
    obj.songs[song['songid']]['artist'] = song['artist'][0]
IndexError: list index out of range
```

The ``artist`` field is empty for the track 21471.
