### ISSUE TITLE
Empty music library leads to crash

### ISSUE THREAD

**Issue by jandechent** [Arn-O/py-kodi-remote-controller#48]
falk@Farnsworth:~/Diverses/Git/py-kodi-remote-controller$ python pykodi.py 127.0.0.1 -p 8080 -u kodi -vv
INFO:root:Kodi controller started in verbosity mode ...
DEBUG:root:... and even in high verbosity mode!
DEBUG:root:call function get_audio_library
DEBUG:root:load albums library in memory
DEBUG:root:call function is_library_files
DEBUG:root:call function is_file
INFO:root:library files check: False
DEBUG:root:get_audio_library_from_server
Loading the Kodi server library, this may be very long

DEBUG:root:call call_api_http
DEBUG:root:command: {'params': {'limits': {'start': 0, 'end': 1}}, 'jsonrpc': '2.0', 'method': 'AudioLibrary.GetSongs', 'id': 1}
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
DEBUG:urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 74
DEBUG:root:url: http://127.0.0.1:8080/jsonrpc
DEBUG:root:status code: 200
DEBUG:root:text: {"id":1,"jsonrpc":"2.0","result":{"limits":{"end":0,"start":0,"total":0}}}
DEBUG:root:call display_result
INFO:root:command processed successfully
DEBUG:root:number of songs: 0
Traceback (most recent call last):
  File "pykodi.py", line 820, in <module>
    main()
  File "pykodi.py", line 817, in main
    remote_controller.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 109, in cmdloop
    self.preloop()
  File "pykodi.py", line 508, in preloop
    get_audio_library(self)
  File "pykodi.py", line 104, in get_audio_library
    get_audio_library_from_server(obj)
  File "pykodi.py", line 148, in get_audio_library_from_server
    pbar.start()
  File "/usr/lib/pymodules/python2.7/progressbar/__init__.py", line 311, in start
    self.update(0)
  File "/usr/lib/pymodules/python2.7/progressbar/__init__.py", line 283, in update
    self.fd.write(self._format_line() + '\r')
  File "/usr/lib/pymodules/python2.7/progressbar/__init__.py", line 243, in _format_line
    widgets = ''.join(self._format_widgets())
  File "/usr/lib/pymodules/python2.7/progressbar/__init__.py", line 223, in _format_widgets
    widget = format_updatable(widget, self)
  File "/usr/lib/pymodules/python2.7/progressbar/widgets.py", line 38, in format_updatable
    if hasattr(updatable, 'update'): return updatable.update(pbar)
  File "/usr/lib/pymodules/python2.7/progressbar/widgets.py", line 184, in update
    return '%3d%%' % pbar.percentage()
  File "/usr/lib/pymodules/python2.7/progressbar/__init__.py", line 208, in percentage
    return self.currval * 100.0 / self.maxval
ZeroDivisionError: float division by zero

**Comment by Arn-O** [comment]
Looks like you do not have any songs in your audio library. Is it correct?

**Comment by jandechent** [comment]
a15d495dbf91c6b4771da6ea37c666f78a397b2c
