### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by crackulator** [Arn-O/py-kodi-remote-controller#62]
When I start the script, I get:
```
Loading the Kodi server library, this may be very long

Songs: 100% [###################################] (28483 in 28483) Time: 0:01:28
Traceback (most recent call last):                  ] (90 in 2545) ETA:  0:00:05
  File "pykodi.py", line 1036, in <module>
    main()
  File "pykodi.py", line 1032, in main
    remote_controller = KodiRemote()
  File "pykodi.py", line 611, in __init__
    get_audio_library(self)
  File "pykodi.py", line 110, in get_audio_library
    get_audio_library_from_server(obj)
  File "pykodi.py", line 240, in get_audio_library_from_server
    if album['artist'][0]:
IndexError: list index out of range
```

**Comment by Arn-O** [comment]
I do not have the case in my library, but it should work now.

**Comment by Arn-O** [comment]
For reference, same issue as #61 not properly fixed with the previous commit.

**Comment by crackulator** [comment]
Verified fixed.

Thanks for sharing this, very fun project.
