### ISSUE TITLE
Crash on album or song search

### ISSUE THREAD

**Issue by crackulator** [Arn-O/py-kodi-remote-controller#63]
Whenever I try to search albums or songs, I get this:

(Kodi (boxy1)) albums_search skull
Traceback (most recent call last):
  File "pykodi.py", line 1036, in <module>
    main()
  File "pykodi.py", line 1033, in main
    remote_controller.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "pykodi.py", line 682, in do_albums_search
    albums_pos = get_albums_search(search_string, self.albums)
  File "pykodi.py", line 294, in get_albums_search
    if search_string in albums[album_id]['artist'].lower():
KeyError: 'artist'

Doesn't seem to matter what I put in for a search term (well, everything that I tried had the same result).
May be related to issue #61/62? I have a very large library.

**Comment by Arn-O** [comment]
Hi.

It looks related to #62, indeed. The size of the library should be OK, the "consistency" is more an issue here. All my library has been cleaned with MusicBrainz, so I do not have albums without artist.

Let me have look into it.

Ar.

**Comment by Arn-O** [comment]
Could you try? Again, I do not have the case, no easy to test on my side.

Thx!

**Comment by crackulator** [comment]
Now I get:

(Kodi (boxy1)) albums_search beautiful
Traceback (most recent call last):
  File "/home/fritz/pykodi/pykodi.py", line 1040, in <module>
    main()
  File "/home/fritz/pykodi/pykodi.py", line 1037, in main
    remote_controller.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/fritz/pykodi/pykodi.py", line 686, in do_albums_search
    albums_pos = get_albums_search(search_string, self.albums)
  File "/home/fritz/pykodi/pykodi.py", line 298, in get_albums_search
    if search_string in albums[album_id]['artist'].lower():
KeyError: 'artist'

**Comment by Arn-O** [comment]
Hi.

Could you delete the pickle files and try again? I guess that the data structures stored in them is wrong.

Ar.

**Comment by crackulator** [comment]
Verified fixed. Brilliant work sir!
