### ISSUE TITLE
KeyError with playlist_show

### ISSUE THREAD

**Issue by Arn-O** [Arn-O/py-kodi-remote-controller#70]
See test result from @Kavod:

```
DEBUG:__main__:call function is_file
DEBUG:__main__:kodi params file found
DEBUG:__main__:call function read_params
DEBUG:__main__:call function set_friendly_name
DEBUG:pykodi:call function get_friendly_name
DEBUG:pykodi:call function is_reachable
DEBUG:pykodi_rpc:call function jsonrpc_ping
DEBUG:pykodi_rpc:call call_api_http
INFO:pykodi_rpc:command: {'jsonrpc': '2.0', 'method': 'JSONRPC.Ping', 'id': 1}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.10
DEBUG:requests.packages.urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 40
DEBUG:pykodi_rpc:url: http://192.168.0.10:8080/jsonrpc
DEBUG:pykodi_rpc:status code: 200
DEBUG:pykodi_rpc:text: {"id":1,"jsonrpc":"2.0","result":"pong"}
DEBUG:pykodi_rpc:call display_result
INFO:pykodi_rpc:command processed successfully
DEBUG:pykodi_rpc:call call_api_http
INFO:pykodi_rpc:command: {'params': {'labels': ['System.FriendlyName']}, 'jsonrpc': '2.0', 'method': 'XBMC.GetInfoLabels', 'id': 1}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.10
DEBUG:requests.packages.urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 75
DEBUG:pykodi_rpc:url: http://192.168.0.10:8080/jsonrpc
DEBUG:pykodi_rpc:status code: 200
DEBUG:pykodi_rpc:text: {"id":1,"jsonrpc":"2.0","result":{"System.FriendlyName":"Kodi (OpenELEC)"}}
DEBUG:pykodi_rpc:call display_result
INFO:pykodi_rpc:command processed successfully
DEBUG:__main__:call function is_file
DEBUG:__main__:call function is_file
DEBUG:__main__:call function get_songs_from_file
DEBUG:__main__:call function do_playlist_add_song
DEBUG:pykodi:call playlist_add_songs
DEBUG:pykodi_rpc:call function playlist_add
DEBUG:pykodi_rpc:call call_api_http
INFO:pykodi_rpc:command: {'params': {'item': {'songid': 32796}, 'playlistid': 0}, 'jsonrpc': '2.0', 'method': 'Playlist.Add', 'id': 1}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.10
DEBUG:requests.packages.urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 38
DEBUG:pykodi_rpc:url: http://192.168.0.10:8080/jsonrpc
DEBUG:pykodi_rpc:status code: 200
DEBUG:pykodi_rpc:text: {"id":1,"jsonrpc":"2.0","result":"OK"}
DEBUG:pykodi_rpc:call display_result
INFO:pykodi_rpc:command processed successfully
DEBUG:__main__:call function do_playlist_show
DEBUG:pykodi:call get_playlist_position
DEBUG:pykodi_rpc:call function player_get_properties
DEBUG:pykodi_rpc:call call_api_http
INFO:pykodi_rpc:command: {'params': {'playerid': 0, 'properties': ['time', 'totaltime', 'percentage', 'position']}, 'jsonrpc': '2.0', 'method': 'Player.GetProperties', 'id': 1}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 192.168.0.10
DEBUG:requests.packages.urllib3.connectionpool:"POST /jsonrpc HTTP/1.1" 200 86
DEBUG:pykodi_rpc:url: http://192.168.0.10:8080/jsonrpc
DEBUG:pykodi_rpc:status code: 200
DEBUG:pykodi_rpc:text: {"error":{"code":-32100,"message":"Failed to execute method."},"id":1,"jsonrpc":"2.0"}
DEBUG:pykodi_rpc:call display_result
ERROR:pykodi_rpc:too bad, something went wrong!
ERROR:pykodi_rpc:error message: Failed to execute method.
Traceback (most recent call last):
  File "pykodi_cmd.py", line 417, in <module>
    main()
  File "pykodi_cmd.py", line 414, in main
    remote_controller.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "pykodi_cmd.py", line 296, in do_playlist_show
    position = kodi.get_playlist_position(self.params)
  File "/home/boris/py-kodi-remote-controller/pykodi.py", line 468, in get_playlist_position
    properties = pk_rpc.player_get_properties(params)
  File "/home/boris/py-kodi-remote-controller/pykodi_rpc.py", line 264, in player_get_properties
    return ret['result']
KeyError: 'result'
```

This may be due to a missing active audio player.

**Comment by Arn-O** [comment]
The latest tests are OK, this issue remains unexplained.
