### ISSUE TITLE
Cannot sync after echonest_delete

### ISSUE THREAD

**Issue by Arn-O** [Arn-O/py-kodi-remote-controller#95]
The internal ``albums`` and ``songs`` dictionaries are missing.

```
(Kodi (OpenELEC)) echonest_delete

WARNING: you are about to delete your taste profile. All your
favorite, ban and skip data will be lost. playcount and rating
data are safe in your Kodi library.

Are you sure (Y/c)? Y

   Your echonest profile has been deleted.

(Kodi (OpenELEC)) albums_sync

Traceback (most recent call last):
  File "pykodi_cmd.py", line 627, in <module>
    main()
  File "pykodi_cmd.py", line 624, in main
    remote_controller.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "pykodi_cmd.py", line 209, in do_albums_sync
    pk.albums_sync(self.params, self.albums, self.log_level == 0)
AttributeError: KodiRemote instance has no attribute 'albums'
```

**Comment by Arn-O** [comment]
Was not related to ``echonest_delete``.
